# Generated by Django 4.2.2 on 2023-09-10 12:07

from django.contrib.auth.hashers import make_password
from django.db import migrations


def populate_users(apps, schema_editor):
    User = apps.get_model("coffee", "User")
    User(
        username='Fred',
        password=make_password('fred'),
        email='someone@yahoo.com',
        slug='fred',
    ).save()

    User(
        username='Nancy',
        password=make_password('nancy'),
        email='someone@yahoo.com',
        slug='nancy',
    ).save()


def populate_cafes(apps, schema_editor):
    Cafe = apps.get_model("coffee", "Cafe")
    User = apps.get_model("coffee", "User")
    Image = apps.get_model("coffee", "Image")

    cafe_name = '41'
    Cafe(
        contributor=User.objects.get(username='Fred'),
        name=cafe_name,
        description='Trendy and newly refurbished\nFriendly atmosphere',
        location='Forest Hill'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=cafe_name),
        name='images/IMG_3510_shopfront.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=cafe_name),
        name='images/IMG_3538.jpeg'
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_users),
        migrations.RunPython(populate_cafes),
    ]
