# Generated by Django 4.2.2 on 2023-09-10 12:07

from django.contrib.auth.hashers import make_password
from django.db import migrations


def populate_users(apps, schema_editor):
    User = apps.get_model("coffee", "User")
    User(
        username='Judy',
        password=make_password('judy'),
        email='someone@yahoo.com',
        slug='judy',
    ).save()


def populate_cafes(apps, schema_editor):
    Cafe = apps.get_model("coffee", "Cafe")
    User = apps.get_model("coffee", "User")
    Image = apps.get_model("coffee", "Image")

    no_41_coffee = 'No. 41 Coffee'
    Cafe(
        contributor=User.objects.get(username='Judy'),
        name=no_41_coffee,
        description='Trendy and newly refurbished.\nFriendly atmosphere.',
        location='Forest Hill'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=no_41_coffee),
        name='images/IMG_3510_shopfront.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=no_41_coffee),
        name='images/IMG_3538.jpeg'
    ).save()

    alexandra_nurseries = 'Alexandra Nurseries'
    Cafe(
        contributor=User.objects.get(username='Judy'),
        name=alexandra_nurseries,
        description='Romantic garden centre with outdoor seating amongst the plants and shrubs.\n'
                    'Friendly family run business.\n'
                    'In winter there is a Christmas market and burger nights with mulled wine on several evenings.',
        location='Sydenham'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=alexandra_nurseries),
        name='images/IMG_3660_shopfront.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=alexandra_nurseries),
        name='images/IMG_3684.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=alexandra_nurseries),
        name='images/IMG_3686.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=alexandra_nurseries),
        name='images/IMG_3687.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=alexandra_nurseries),
        name='images/IMG_3688.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=alexandra_nurseries),
        name='images/IMG_3689.jpeg'
    ).save()

    penge_general = 'Penge General Store'
    Cafe(
        contributor=User.objects.get(username='Judy'),
        name=penge_general,
        description='Trendy deli shop selling upmarket produce and speciality coffee for take-away.\n'
                    'Very friendly and helpful staff, this is a Penge gem.',
        location='Penge'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=penge_general),
        name='images/IMG_3654_shopfront.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=penge_general),
        name='images/IMG_3656.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=penge_general),
        name='images/IMG_3659.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=penge_general),
        name='images/IMG_3681.jpeg'
    ).save()

    four_boroughs = 'Four Boroughs'
    Cafe(
        contributor=User.objects.get(username='Judy'),
        name=four_boroughs,
        description='Situated in a beautiful newly renovated courtyard.\n'
                    'Lots of outdoor seating available away from traffic and noise.',
        location='Loughborough Junction'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=four_boroughs),
        name='images/IMG_3554_shopfront.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=four_boroughs),
        name='images/IMG_3551_shopfront.jpeg'
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_users),
        migrations.RunPython(populate_cafes),
    ]
