# Generated by Django 4.2.2 on 2023-08-11 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quality', models.IntegerField(choices=[(1, 'One Bean'), (2, 'Two Beans'), (3, 'Three Beans'), (4, 'Four Beans'), (5, 'Five Beans')])),
                ('latte_art', models.IntegerField(choices=[(1, 'One Bean'), (2, 'Two Beans'), (3, 'Three Beans'), (4, 'Four Beans'), (5, 'Five Beans')])),
                ('barrista_friendliness', models.IntegerField(choices=[(1, 'One Bean'), (2, 'Two Beans'), (3, 'Three Beans'), (4, 'Four Beans'), (5, 'Five Beans')])),
                ('price', models.IntegerField(choices=[(1, 'One Bean'), (2, 'Two Beans'), (3, 'Three Beans'), (4, 'Four Beans'), (5, 'Five Beans')])),
                ('opening_hours', models.IntegerField(choices=[(1, 'One Bean'), (2, 'Two Beans'), (3, 'Three Beans'), (4, 'Four Beans'), (5, 'Five Beans')])),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.coffeeshop')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
