# Generated by Django 4.2.2 on 2023-09-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20230910_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='inspiration_1',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='inspiration_2',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='inspiration_3',
        ),
        migrations.AddField(
            model_name='poem',
            name='inspiration',
            field=models.TextField(default='Smooth and mellow with hints of orange. Roasted.Bubbly and truly delicious.. invigorating', max_length=750),
            preserve_default=False,
        ),
    ]
