# Generated by Django 4.2.2 on 2023-09-12 12:45

from django.db import migrations


def populate_cafes(apps, schema_editor):
    Cafe = apps.get_model("coffee", "Cafe")
    User = apps.get_model("coffee", "User")
    Image = apps.get_model("coffee", "Image")

    kaffeine = 'Kaffeine'
    Cafe(
        contributor=User.objects.get(username='Fred'),
        name=kaffeine,
        description='Open since 2009 and still regarded as a leading benchmark setting cafe'
                    'of the London speciality coffee industry\n'
                    'Located in the beating heart of Fitzrovia, just three minutes from Oxford Circus',
        location='London City'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=kaffeine),
        name='images/IMG_3662_shopfront.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=kaffeine),
        name='images/IMG_3664.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=kaffeine),
        name='images/IMG_3665.jpeg'
    ).save()

    dukes_caffe = "Duke's Cafe"
    Cafe(
        contributor=User.objects.get(username='Fred'),
        name=dukes_caffe,
        description='A third generation family-run business that is passionate about serving quality food and coffee\n'
                    'to customers in the West End.',
        location='London City'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=dukes_caffe),
        name='images/IMG_3674_shopfront.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=dukes_caffe),
        name='images/IMG_3666.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=dukes_caffe),
        name='images/IMG_3667.jpeg'
    ).save()

    Image(
        cafe=Cafe.objects.get(name=dukes_caffe),
        name='images/IMG_3670.jpeg'
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_data_migrate'),
    ]

    operations = [
        migrations.RunPython(populate_cafes),
    ]
