# Generated by Django 4.2.2 on 2023-09-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_cafe_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='number_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='sum_ratings',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
