# Generated by Django 4.2.2 on 2023-09-09 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_alter_adjective_adjective'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=250)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.cafe')),
            ],
        ),
        migrations.DeleteModel(
            name='Adjective',
        ),
    ]
