# Generated by Django 4.2.2 on 2023-09-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_cafe_number_ratings_cafe_sum_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='sum_ratings',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
