# Generated by Django 4.2.2 on 2023-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_coffeedescription_delete_adjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='haiku_check',
            field=models.BooleanField(default=False),
        ),
    ]
