# Generated by Django 4.2.2 on 2023-09-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_alter_cafe_sum_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='number_ratings',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='sum_ratings',
        ),
    ]
