# Generated by Django 4.2.2 on 2023-09-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_rename_haiku_check_cafe_check_for_haiku'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='haiku_line_1',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poem',
            name='haiku_line_2',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poem',
            name='haiku_line_3',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
