# Generated by Django 4.2.2 on 2023-09-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_poem_haiku_line_1_poem_haiku_line_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='haiku_line_1',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='haiku_line_2',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='haiku_line_3',
        ),
    ]
